cache: bundler
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - ruby-head
  - jruby-19mode
  - rbx-2
install:
  - bundle install --retry=3 --without dev,docs
script:
  - bundle exec rspec
